### ISSUE TITLE
Autosuggestion completion no longer works

### ISSUE THREAD

**Issue by john9631** [jonathanslenders/ptpython#268]
Thanks for the amazing tool Jonathan.   

I've got a recent problem (pretty sure it didn't exist before I did a complete Python 3.7.0 packages upgrade yesterday.  Its been working on 3.7 since the betas.  I'm currently on ptpython 2.0.3 and prompt-toolkit 2.0.6.

To replicate:  I have a history file in .ptpython and have xxx'd out my config file so it starts default.  Open in terminal with ptpython.  F2, Autosuggestion on.   

Type start of command from history & it shows a completion option  https://i.imgur.com/Ryvvwff.png

Last week I would have used right arrow to complete followed by enter.  This no longer works.  Nor does ctrl e or anything else I've tried.   Any ideas?

Thanks, John

**Comment by john9631** [comment]
Reverted to 0.41, 1.0.15 and it works again.

**Comment by jonathanslenders** [comment]
This should fix it: https://github.com/jonathanslenders/ptpython/commit/0106ea65390467f3e4ea82b927256a7cca3db888
Can you try again from the master branch, and see whether it works?

**Comment by john9631** [comment]
I may be misunderstanding what you mean by "Can you try again from the master branch, and see whether it works?"

I cloned `jonathanslenders/ptpython`, `cd` and ran `sudo python3.7 setup.py install`

The problem remained.

**Comment by afrieder** [comment]
I also had this issue and installing from master seems to have resolved it.

**Comment by john9631** [comment]
It seems I had some conflicts.  A cleanout of ptpythons & prompt_toolkits followed by the steps above has resulted in success.

So, thanks again for such excellent packages.  Closed.
